import{cmsFetch}from"../lib/cmsApi.js";
import React,{useCallback,useEffect,useMemo,useState} from "react";
import {ArrowLeft,ArrowRight,CalendarDays,Check,ChevronLeft,ChevronRight,Clock,Loader2,RefreshCw,ShieldCheck} from "lucide-react";
import FeedbackModal from "./FeedbackModal.jsx";
import {track} from "./Analytics.jsx";
const pad=n=>String(n).padStart(2,"0"),dateKey=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
export default function BookingSection(){
 const [settings,setSettings]=useState(null),[cursor,setCursor]=useState(()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth(),1)}),[selectedDate,setSelectedDate]=useState(''),[slots,setSlots]=useState([]),[selectedSlot,setSelectedSlot]=useState(null),[loading,setLoading]=useState(false),[checking,setChecking]=useState(''),[step,setStep]=useState(1),[submitting,setSubmitting]=useState(false),[modal,setModal]=useState({open:false}),[status,setStatus]=useState('');
 useEffect(()=>{cmsFetch('/api/booking/settings').then(r=>r.ok?r.json():null).then(setSettings).catch(()=>{})},[]);
 const days=useMemo(()=>{const y=cursor.getFullYear(),m=cursor.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),a=[];for(let i=0;i<first.getDay();i++)a.push(null);for(let d=1;d<=last.getDate();d++)a.push(new Date(y,m,d));return a},[cursor]);
 const refresh=useCallback(async(key,{silent=false}={})=>{if(!key)return[];if(!silent)setLoading(true);try{const r=await cmsFetch(`/api/booking/availability?date=${encodeURIComponent(key)}&_=${Date.now()}`,{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to load availability.');const fresh=j.slots||[];setSlots(fresh);setSelectedSlot(c=>c&&fresh.some(s=>s.start===c.start)?c:null);if(!fresh.length&&!silent)setStatus('No available times on this date. Choose another day.');return fresh}catch(e){if(!silent)setStatus(e.message);return[]}finally{if(!silent)setLoading(false)}},[]);
 async function chooseDate(d){const key=dateKey(d);if(key<settings.today||key>settings.maxDate)return;setSelectedDate(key);setSelectedSlot(null);setStatus('');setSlots([]);setStep(2);await refresh(key)}
 useEffect(()=>{if(!selectedDate)return;const fn=()=>refresh(selectedDate,{silent:true}),timer=setInterval(fn,15000),focus=()=>fn(),vis=()=>document.visibilityState==='visible'&&fn();window.addEventListener('focus',focus);document.addEventListener('visibilitychange',vis);return()=>{clearInterval(timer);window.removeEventListener('focus',focus);document.removeEventListener('visibilitychange',vis)}},[selectedDate,refresh]);
 async function chooseSlot(slot){if(checking)return;setChecking(slot.start);const fresh=await refresh(selectedDate,{silent:true}),free=fresh.find(x=>x.start===slot.start);setChecking('');if(!free){setStatus('That time was just taken and has been removed.');return}setSelectedSlot(free);setStatus('');setStep(3)}
 async function submit(e){e.preventDefault();const form=e.currentTarget;if(!selectedSlot)return;const fresh=await refresh(selectedDate,{silent:true}),free=fresh.find(x=>x.start===selectedSlot.start);if(!free){setStep(2);setSelectedSlot(null);return setStatus('That time is no longer available. Please choose another time.')}const body=Object.fromEntries(new FormData(form));body.start=free.start;setSubmitting(true);try{const r=await cmsFetch('/api/booking',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to complete booking.');form.reset();track('booking_completed',{duration:settings.durationMinutes});setModal({open:true,type:'success',title:'Your discovery call is booked.',message:j.message||settings.successMessage});setStep(1);setSelectedDate('');setSelectedSlot(null);setSlots([])}catch(e){if(String(e.message).includes('no longer')){setStep(2);setSelectedSlot(null);await refresh(selectedDate,{silent:true})}setModal({open:true,type:'error',title:'We couldn’t complete the booking.',message:e.message})}finally{setSubmitting(false)}}
 if(!settings?.enabled)return null;const monthLabel=cursor.toLocaleDateString('en-CA',{month:'long',year:'numeric'}),dateLabel=selectedDate?new Date(`${selectedDate}T12:00:00`).toLocaleDateString('en-CA',{weekday:'long',month:'long',day:'numeric'}):'';
 return <section className="booking-v37 booking-v60" id="book-call"><div className="v14-wrap booking-v37-layout"><div className="booking-v37-copy"><span className="story-kicker">DISCOVERY CALL</span><h2>{settings.title}</h2><p>{settings.subtitle}</p><div className="booking-v37-facts"><span><Clock size={16}/>{settings.durationMinutes} minutes</span><span><CalendarDays size={16}/>{settings.hoursLabel}</span><span><ShieldCheck size={16}/>Live conflict checking</span></div></div><div className="booking-v37-panel booking-step-panel"><div className="booking-stepper">{['Choose date','Choose time','Your details'].map((x,i)=><div className={step===i+1?'active':step>i+1?'done':''} key={x}><span>{step>i+1?<Check size={11}/>:i+1}</span><strong>{x}</strong></div>)}</div>
 {step===1&&<div className="booking-step-content"><div className="booking-step-heading"><span>STEP 01</span><h3>Choose a date.</h3><p>Only working days inside the current booking window are selectable.</p></div><div className="booking-v37-calendar booking-calendar-large"><div className="booking-month"><button onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()-1,1))}><ChevronLeft size={17}/></button><strong>{monthLabel}</strong><button onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()+1,1))}><ChevronRight size={17}/></button></div><div className="booking-weekdays">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=><span key={x}>{x}</span>)}</div><div className="booking-days">{days.map((d,i)=>{if(!d)return <span className="booking-day-empty" key={i}/>;const key=dateKey(d),disabled=key<settings.today||key>settings.maxDate||!(settings.workingDays||[]).includes(d.getDay());return <button key={key} disabled={disabled} className={selectedDate===key?'selected':''} onClick={()=>chooseDate(d)}><span>{d.getDate()}</span></button>})}</div></div></div>}
 {step===2&&<div className="booking-step-content"><button className="booking-back-step" onClick={()=>setStep(1)}><ArrowLeft size={13}/>Change date</button><div className="booking-step-heading"><span>STEP 02 / {dateLabel.toUpperCase()}</span><h3>Choose an available time.</h3><p>These times are checked against website bookings, manual blocks and your connected calendar.</p></div>{loading?<div className="booking-loading"><Loader2 size={17}/>Checking live availability…</div>:slots.length?<div className="booking-slot-grid booking-slot-grid-large">{slots.map(s=><button disabled={!!checking} key={s.start} onClick={()=>chooseSlot(s)}>{checking===s.start?<Loader2 size={12}/>:null}{s.label}</button>)}</div>:<div className="booking-empty-state"><p>{status||'No times are available on this date.'}</p><button onClick={()=>setStep(1)}>Choose another date</button></div>}<button className="booking-refresh" onClick={()=>refresh(selectedDate)}><RefreshCw size={13}/>Refresh live availability</button></div>}
 {step===3&&<div className="booking-step-content"><button className="booking-back-step" onClick={()=>setStep(2)}><ArrowLeft size={13}/>Change time</button><div className="booking-step-heading"><span>STEP 03</span><h3>Tell us what we’re discussing.</h3><p>{dateLabel} · {selectedSlot?.label} · {settings.durationMinutes} minutes</p></div><form className="booking-v37-form booking-form-step" onSubmit={submit}><div className="booking-form-grid"><label>Name<input name="name" required placeholder="Your name"/></label><label>Email<input name="email" type="email" required placeholder="you@company.com"/></label><label>Company<input name="company" placeholder="Company name"/></label><label>Phone *<input name="phone" type="tel" required inputMode="tel" autoComplete="tel" minLength="7" placeholder="Phone number"/></label></div><label>What would you like to discuss?<textarea name="notes" rows="4" placeholder="The product, system, workflow or business problem…"/></label><input className="booking-honeypot" name="website" tabIndex="-1" autoComplete="off"/><button className="booking-submit" disabled={submitting}>{submitting?<><Loader2 size={16}/>Booking…</>:<>Confirm discovery call <ArrowRight size={16}/></>}</button></form></div>}
 {status&&step===2&&slots.length>0&&<div className="booking-status info">{status}</div>}</div></div><FeedbackModal {...modal} onClose={()=>setModal(m=>({...m,open:false}))}/></section>
}
