import React,{lazy,Suspense} from "react";
import HomePage from "./pages/HomePage.jsx";
import CommandPalette from "./components/CommandPalette.jsx";
import Analytics from "./components/Analytics.jsx";
import SmoothCursor from "./components/SmoothCursor.jsx";
import SiteMotion from "./components/SiteMotion.jsx";
const CareersPage=lazy(()=>import('./pages/CareersPage.jsx'));const JobDetailPage=lazy(()=>import('./pages/JobDetailPage.jsx'));const LegalPage=lazy(()=>import('./pages/LegalPage.jsx'));const BookingPage=lazy(()=>import('./pages/BookingPage.jsx'));const ManageBookingPage=lazy(()=>import('./pages/ManageBookingPage.jsx'));const ServicesPage=lazy(()=>import('./pages/ServicesPage.jsx'));const ServiceDetailPage=lazy(()=>import('./pages/ServiceDetailPage.jsx'));const WorkPage=lazy(()=>import('./pages/WorkPage.jsx'));const CaseStudyPage=lazy(()=>import('./pages/CaseStudyPage.jsx'));const InsightsPage=lazy(()=>import('./pages/InsightsPage.jsx'));const InsightPage=lazy(()=>import('./pages/InsightPage.jsx'));const SystemBuilderPage=lazy(()=>import('./pages/SystemBuilderPage.jsx'));const NotFoundPage=lazy(()=>import('./pages/NotFoundPage.jsx'));
const fallback=<div className="route-loading">Loading Xynysys…</div>;
export default function App(){const path=window.location.pathname.replace(/\/+$/,"")||"/";let page;if(path==="/")page=<HomePage/>;else if(path==="/careers")page=<CareersPage/>;else if(path.startsWith('/careers/'))page=<JobDetailPage slug={decodeURIComponent(path.slice(9))}/>;else if(path==="/book-call")page=<BookingPage/>;else if(path==="/manage-booking")page=<ManageBookingPage/>;else if(path==="/services")page=<ServicesPage/>;else if(path.startsWith('/services/'))page=<ServiceDetailPage slug={decodeURIComponent(path.slice(10))}/>;else if(path==="/work")page=<WorkPage/>;else if(path.startsWith('/work/'))page=<CaseStudyPage slug={decodeURIComponent(path.slice(6))}/>;else if(path==="/insights")page=<InsightsPage/>;else if(path.startsWith('/insights/'))page=<InsightPage slug={decodeURIComponent(path.slice(10))}/>;else if(path==="/system-builder")page=<SystemBuilderPage/>;else if(['/privacy','/terms','/cookies','/accessibility'].includes(path))page=<LegalPage type={path.slice(1)}/>;else page=<NotFoundPage/>;return <><SmoothCursor/><SiteMotion/><Analytics/><Suspense fallback={fallback}>{page}</Suspense><CommandPalette/></>}
